apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: buildah
spec:
  workspaces:
  - name: source
  params:
  - name: IMAGE
    type: string
  steps:
  - name: build
    image: quay.io/buildah/stable
    workingDir: $(workspaces.source.path)
    script: |
      buildah bud -f Dockerfile -t $(params.IMAGE) .
      buildah push $(params.IMAGE)
