apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservices-platform
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    repoURL: https://github.com/gamasy/microservices-platform.git
    path: .
    targetRevision: HEAD
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
