apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: bkend-monitor
spec:
  selector:
    matchLabels:
      app: backend
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
